application: isabella
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: adminpagehandlers.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: .*
  script: m1.py
